[project]
name = "LaravelApp"
languages = { php = "8.3", node = "20" }

[env]
PORT = "80"

[build]
command = "if [ ! -f .env ]; then cp .env.example .env; fi && if [ ! -f database/database.sqlite ]; then mkdir -p database && touch database/database.sqlite && chmod 777 database/database.sqlite; fi && composer install --optimize-autoloader --no-dev && npm install && npm run build && php artisan key:generate && php artisan migrate --force"

[run]
command = "php artisan serve --host=0.0.0.0 --port=$PORT"
