[phases.setup]
nixPkgs = [
    'php83',
    'php83Packages.composer',
    'nodejs',
    'sqlite',
    'git'
]

[phases.install]
cmds = [
    'composer install --no-interaction --no-progress',
    'composer dump-autoload --optimize',
    'npm install'
]

[phases.build]
cmds = [
    'npm run build',
    'mkdir -p /app/database',
    'touch /app/database/database.sqlite',
    'chmod 777 /app/database/database.sqlite',
    'php artisan migrate --force'
]

[start]
cmd = 'php artisan serve --host=0.0.0.0 --port=${PORT:-80}'

[variables]
PORT = "80"
APP_ENV = "production"
APP_DEBUG = "false"
DB_CONNECTION = "sqlite"
DB_DATABASE = "/app/database/database.sqlite"

[environment]
NODE_VERSION = "20"
PHP_VERSION = "8.3"
