[phases.setup]
nixPkgs = ['php83', 'nodejs', 'sqlite', 'git']

[phases.install]
cmds = [
    'cp .env.example .env',
    'composer install',
    'composer dump-autoload',
    'npm install'
]

[phases.build]
cmds = [
    'npm run build',
    'touch database/database.sqlite',
    'chmod -R 777 .',
    'chmod 777 database/database.sqlite',
    'chmod -R 777 database',
    'php artisan key:generate',
    'php artisan migrate --force'
]

[start]
cmd = 'php artisan serve --host=0.0.0.0 --port=${PORT:-80}'

[variables]
PORT = "80"
APP_ENV = "production"
APP_DEBUG = "false"
DB_CONNECTION = "sqlite"
DB_DATABASE = "/workspace/database/database.sqlite"

[environment]
NODE_VERSION = "20"
PHP_VERSION = "8.3"
